---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: flux-system
spec:
  releaseName: external-dns
  targetNamespace: external-dns
  interval: 15m
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: external-dns
      version: 6.13.3
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 15m
  install:
    crds: CreateReplace
    createNamespace: true
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
      remediateLastFailure: true
  values:
    provider: cloudflare
    cloudflare:
      proxied: false
      ## @param cloudflare.secretName When using the Cloudflare provider, it's the name of the secret containing cloudflare_api_token or cloudflare_api_key.
      ## This ignores cloudflare.apiToken, and cloudflare.apiKey
      ##
      secretName: "cloudflare-api-token-secret"
    metrics:
      enabled: true
