---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: renovate
  namespace: flux-system
spec:
  releaseName: renovate
  targetNamespace: renovate
  install:
    createNamespace: true
  interval: 15m
  chart:
    spec:
      # renovate: registryUrl=https://docs.renovatebot.com/helm-charts
      chart: renovate
      version: 34.152.4
      sourceRef:
        kind: HelmRepository
        name: renovate
        namespace: flux-system
      interval: 15m

  values:
    cronjob:
      schedule: "@hourly"

    ssh_config:
      enabled: true
      existingSecret: renovate-credentials

    existingSecret: renovate-env

    renovate:
      config: |
        {
         "printConfig": false,
         "binarySource": "install",
         "repositories": ["corgis-social/k8s-flux"],
         "requireConfig": "required",
         "dependencyDashboard": true,
         "flux": {
           "fileMatch": ["cluster/flux-system/flux-system.yaml$"]
         },
         "helm-values": {"fileMatch": [
           "infra/.+/helmrelease\\.yaml$",
           "apps/.+/helmrelease\\.yaml$"
         ]},
         "rebaseWhen": "behind-base-branch",
         "regexManagers": [
           {
             "fileMatch": ["cluster/.+\\.yaml$"],
             "matchStrings": [
               "registryUrl=(?<registryUrl>.*?)\n *chart: (?<depName>.*?)\n *version: (?<currentValue>.*)\n"
             ],
             "datasourceTemplate": "helm"
           }
         ],
         "packageRules": [
           {
             "matchDatasources": ["docker"],
             "versioning": "semver"
           },
           {"matchUpdateTypes": ["major"], "labels": ["type/major"]},
           {
             "matchUpdateTypes": ["minor"], "labels": ["type/minor"],                                                                           
             "automerge": true
           },
           {
             "matchUpdateTypes": ["patch"], "labels": ["type/patch"],                                                                           
             "automerge": true
           },
           {
             "matchDatasources": ["helm"],
             "matchUpdateTypes": ["minor"],
             "semanticCommitType": "feat",
             "semanticCommitScope": "helm",                                                                           
             "automerge": true
           },
           {
             "matchDatasources": ["helm"],
             "matchUpdateTypes": ["patch"],
             "semanticCommitType": "fix",
             "semanticCommitScope": "helm",                                                                           
             "automerge": true
           },
           {"ignoreTests": true, "matchUpdateTypes": ["minor", "patch"]},
           {"matchDatasources": ["helm"], "ignoreDeprecated": true}
         ],
         "regexManagers": [
            {
              "fileMatch": [
                "cluster/.+\\.yaml$"
              ],
              "matchStrings": [
                "registryUrl=(?<registryUrl>.*?)\n *chart: (?<depName>.*?)\n *version: (?<currentValue>.*)\n"
              ],
              "datasourceTemplate": "helm"
            }
          ]
        }
