---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  releaseName: cert-manager
  targetNamespace: cert-manager
  interval: 15m
  chart:
    spec:
      # renovate: registryUrl=https://charts.jetstack.io
      chart: cert-manager
      version: v1.10.0
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
      interval: 15m
  install:
    crds: CreateReplace
    createNamespace: true
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
      remediateLastFailure: true
  values:
    installCRDs: true
