---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: mastodon
  namespace: flux-system
spec:
  interval: 30m0s
  # disabled until https://github.com/mastodon/chart/issues/34 is addressed
  # url: https://github.com/mastodon/chart.git
  url: https://github.com/dbsanfte/chart.git
  ref:
    # see above comment on fix
    # branch: main
    branch: "fix-#34"
