---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: mastodon
  namespace: flux-system
spec:
  interval: 30m0s
  # disabled until https://github.com/mastodon/chart/issues/34 is addressed
  # url: https://github.com/mastodon/chart
  url: https://github.com/dbsanfte/chart
  ref:
    # see above comment on fix
    # branch: main
    # commit sha for branch fix-#34
    commit: e71e990db18bf7730f89111786dbb20c942d98d4
