---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 30m0s
  dependsOn:
  - name: infra
  path: ./apps
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 15m
  validation: client
  wait: true
