---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: flux-system
spec:
  releaseName: metrics-server
  targetNamespace: kube-system
  interval: 15m
  chart:
    spec:
      # renovate: registryUrl=https://kubernetes-sigs.github.io/metrics-server/
      chart: metrics-server
      version: 3.8.2
      sourceRef:
        kind: HelmRepository
        name: metrics-server
        namespace: flux-system
      interval: 15m
  values:
    apiService:
      create: "true"
    args:
      - --kubelet-insecure-tls=true
      - --kubelet-preferred-address-types=InternalIP
