---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitlab-runner
  namespace: flux-system
spec:
  releaseName: gitlab-runner
  targetNamespace: gitlab
  install:
    createNamespace: true
  interval: 15m
  chart:
    spec:
      # gitlab-runner: registryUrl=https://charts.gitlab.io
      chart: gitlab-runner
      version: 0.49.2
      sourceRef:
        kind: HelmRepository
        name: gitlab
        namespace: flux-system
      interval: 15m

  values:
    gitlabUrl: https://gitlab.com/
    rbac:
      create: true
    runners:
      config: |
        [[runners]]
          name = "renovater"
          executor = "docker"
          limit = 1
          [runners.custom_build_dir]
          [runners.docker]
            tls_verify = false
            image = "alpine"
            privileged = false
            disable_entrypoint_overwrite = false
            oom_kill_disable = false
            disable_cache = false
            volumes = ["/certs/client", "/cache", "/tmp:/tmp:rw", "/var/run/docker.sock:/var/run/docker.sock"]
            shm_size = 0
          [runners.cache]
            [runners.cache.s3]
            [runners.cache.gcs]
          [runners.custom]
            run_exec = ""
      secret: gitlab-runner
      locked: true
      protected: true
      privileged: true

