apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: corgis-social
  namespace: mastodon
spec:
  secretName: tls-corgis.social
  issuerRef:
    name: cloudflare-cluster-issuer
    kind: ClusterIssuer
  commonName: 'corgis.social'
  dnsNames:
    - 'corgis.social'
    - 'www.corgis.social'
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: assets-corgis-social
  namespace: mastodon
spec:
  secretName: tls-assets.corgis.social
  issuerRef:
    name: cloudflare-cluster-issuer
    kind: ClusterIssuer
  commonName: 'assets.corgis.social'
  dnsNames:
    - 'assets.corgis.social'

