apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../charts
resources:
- flux-system.yaml
- flux-sync.yaml
#- notification-provider.yaml
#- notification-provider-secret.yaml
patchesStrategicMerge:
- ./flux-patches.yaml
